add-login-route
thecodezone/dt-launcher pull request #10
Opened 2024-01-05 11:46 UTC by Perumal605

2024-01-05 15:11 UTC, incraigulous requested changes

2024-01-09 06:01 UTC, Perumal605 commented on src/Controllers/UserController.php
> +		$require_login = get_option('is_user_logged_in');
@incraigulous Changes updated.

2024-01-09 15:55 UTC, incraigulous requested changes

2024-01-09 15:55 UTC, incraigulous commented on src/Controllers/UserController.php
> +		if ($require_login === 1) {
@Perumal605 , please the require login check here since this is now handled by the LoggedOut middleware.

2024-01-09 16:00 UTC, incraigulous commented on src/Controllers/UserController.php
> +		$require_login = get_option('require_login');
@Perumal605 , please change the option name to "dt_launcher_require_login" to make sure it doesn't conflict with any other options set by the theme or plugins.

2024-01-10 14:24 UTC, incraigulous approved these changes

2024-01-10 14:25 UTC, merged